---
- name: "Copy certificates and keys for {{ project_name }}"
  import_role:
    role: service-cert-copy
  vars:
    project_services: "{{ loadbalancer_services }}"
  when:
    - kolla_copy_ca_into_containers | bool

- name: "Copy certificates and keys for MariaDB "
  import_role:
    role: service-cert-copy
  vars:
    project_services: "{{ loadbalancer_services }}"
    project_name: mariadb
  when: database_enable_tls_backend | bool


- name: "Copy certificates and keys for Proxysql"
  import_role:
    role: service-cert-copy
  vars:
    project_services: "{{ loadbalancer_services }}"
    project_name: "proxysql"
  when: database_enable_tls_internal | bool
