network:
    version: 2
    ethernets:
        eth1:
            mtu: 9000
        eth2:
            mtu: 9000
    bonds:
        bond0:
            interfaces:
            - eth1
            - eth2
            mtu: 9000
            parameters:
                lacp-rate: fast
                mii-monitor-interval: 100
                mode: 802.3ad
                transmit-hash-policy: layer3+4
    vlans:
        bond0.10:
            id: 10
            link: bond0
        bond0.20:
            id: 20
            link: bond0
        bond0.30:
            id: 30
            link: bond0
        bond0.40:
            id: 40
            link: bond0
    bridges:
        br-mgmt:
            addresses:
            - 172.29.236.72/22
            interfaces:
            - bond0.10
            nameservers:
                addresses:
                - 172.29.236.1
        br-storage:
            addresses:
            - 172.21.244.72/22
            interfaces:
            - bond0.20
            mtu: 9000
            openvswitch: {}
        br-vxlan:
            addresses:
            - 172.29.240.72/22
            interfaces:
            - bond0.30
        br-provider:
            interfaces:
            - bond0
