aodh_wsgi_processes: 1
aodh_wsgi_threads: 1
barbican_wsgi_processes: 1
barbican_wsgi_threads: 1
blazar_wsgi_processes: 1
blazar_wsgi_threads: 1
ceilometer_notification_workers: 1
cinder_osapi_volume_workers_max: 1
cinder_wsgi_buffer_size: 16384
cinder_wsgi_processes: 1
cinder_wsgi_threads: 1
cloudkitty_wsgi_processes: 1
cloudkitty_wsgi_threads: 1
galera_innodb_log_buffer_size: 4M
galera_monitoring_allowed_source: 0.0.0.0/0
galera_my_cnf_overrides:
  mysqld:
    innodb_buffer_pool_size: 16M
    max_allowed_packet: 8M
    read_buffer_size: 64K
    sort_buffer_size: 8M
    thread_cache_size: '8'
    thread_stack: 192K
    tmp_table_size: 8M
galera_wsrep_provider_options:
  - option: gcache.size
    value: 4M
glance_api_threads: 1
glance_api_workers: 1
glance_wsgi_processes: 1
glance_wsgi_threads: 1
gnocchi_metricd_workers: 1
gnocchi_wsgi_processes: 1
gnocchi_wsgi_threads: 1
heat_api_threads: 1
heat_api_workers: 1
heat_wsgi_buffer_size: 16384
heat_wsgi_processes: 1
heat_wsgi_threads: 1
horizon_wsgi_processes: 1
horizon_wsgi_threads: 1
ironic_inspector_wsgi_processes: 1
ironic_inspector_wsgi_threads: 1
ironic_wsgi_processes: 1
ironic_wsgi_threads: 1
keystone_httpd_mpm_max_spare_threads: 10
keystone_httpd_mpm_min_spare_threads: 5
keystone_httpd_mpm_start_servers: 2
keystone_httpd_mpm_thread_child: 15
keystone_httpd_mpm_thread_limit: 15
keystone_wsgi_processes: 2
keystone_wsgi_threads: 2
lxc_container_backing_store: dir
lxc_container_bind_mounts:
  - container_directory: /openstack/src
    host_directory: /home/zuul/src
  - container_directory: /opt/cache/files
    host_directory: /opt/cache/files
lxc_net_address: 10.255.255.1
lxc_net_dhcp_range: 10.255.255.2,10.255.255.253
lxc_net_mtu: 1500
lxc_net_netmask: 255.255.255.0
magnum_conductor_workers: 1
magnum_wsgi_processes: 1
manila_osapi_share_workers: 2
manila_wsgi_buffer_size: 65535
manila_wsgi_processes: 1
manila_wsgi_threads: 1
mistral_wsgi_processes: 1
mistral_wsgi_threads: 1
neutron_api_threads: 2
neutron_api_workers: 1
neutron_metadata_workers: 1
neutron_num_sync_threads: 1
neutron_plugin_type: ml2.ovn
neutron_rpc_workers: 1
neutron_wsgi_processes: 1
nova_api_threads: 1
nova_conductor_workers: 1
nova_metadata_workers: 1
nova_osapi_compute_workers: 1
nova_scheduler_workers: 1
nova_service_negate:
  - nova-agent.service
  - nova-resetnetwork.service
nova_wsgi_buffer_size: 16384
nova_wsgi_processes: 1
nova_wsgi_threads: 1
octavia_management_net_subnet_allocation_pools: 172.29.232.150-172.29.235.250
octavia_management_net_subnet_cidr: 172.29.232.0/22
octavia_wsgi_buffer_size: 16384
octavia_wsgi_processes: 1
octavia_wsgi_threads: 1
openstack_hosts_journald_config:
  RateLimitBurst: 600
  RateLimitIntervalSec: 60
  RuntimeMaxFileSize: 100M
  RuntimeMaxUse: 2G
  SystemMaxFileSize: 100M
  SystemMaxUse: 4G
openstack_hosts_package_state: latest
openstack_user_kernel_options:
  - key: kernel.printk
    value: 4 1 7 4
placement_wsgi_buffer_size: 16384
placement_wsgi_processes: 1
placement_wsgi_threads: 1
rally_install: true
repo_nginx_threads: 2
sahara_api_workers: 1
sahara_wsgi_buffer_size: 16384
sahara_wsgi_processes: 1
sahara_wsgi_threads: 1
senlin_api_threads: 1
senlin_wsgi_processes: 1
senlin_wsgi_threads: 1
swift_account_server_replicator_workers: 1
swift_account_server_workers: 1
swift_container_server_workers: 1
swift_object_replicator_workers: 1
swift_object_server_workers: 1
swift_proxy_server_workers: 1
swift_proxy_server_workers_capped: 1
swift_proxy_server_workers_not_capped: 1
swift_server_replicator_workers: 1
tempest_install: true
tempest_network_ping_gateway: true
tempest_private_net_provider_type: geneve
tempest_public_net_physical_name: vlan
tempest_public_subnet_allocation_pools: 172.29.249.110-172.29.249.200
tempest_public_subnet_cidr: 172.29.248.0/22
tempest_run: true
tempest_tempest_conf_overrides_neutron:
  network-feature-enabled:
    api_extensions: agent,allowed-address-pairs,binding,dhcp_agent_scheduler,ext-gw-mode,external-net,extra_dhcp_opt,extra_dhcp_optagent,extraroute,l3_agent_scheduler,metering,provider,quotas,router,security-group,service-type,subnet_allocation
tempest_test_includelist:
  - neutron_tempest_plugin.api.test_networks*
  - tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops
trove_api_workers: 1
trove_conductor_workers: 1
trove_service_net_setup: true
trove_wsgi_processes: 1
trove_wsgi_threads: 1
venv_wheel_build_enable: false
zun_api_threads: 1
zun_wsgi_processes: 1
zun_wsgi_threads: 1

## Installation method for OpenStack services
install_method: source

## Debug and Verbose options.
debug: true

# If you wish to change the dhcp_domain configured for both nova and neutron
dhcp_domain: openstacklocal

## Ceph cluster fsid (must be generated before first run)
generate_fsid: true

## ceph-ansible settings
monitor_address_block: "{{ cidr_networks.storage }}"
public_network: "{{ cidr_networks.storage }}"
cluster_network: "{{ cidr_networks.storage }}"
journal_size: 10240 # size in MB
openstack_config: true
# For configuring a backend in Cinder to store volumes in Ceph.
cinder_ceph_client: cinder
# For configuring the Ceph backend for Glance to store images in Ceph.
glance_ceph_client: glance
glance_default_store: rbd
glance_rbd_store_pool: images
# Configuration for Nova compute and libvirt to store ephemeral discs in Ceph.
nova_libvirt_images_rbd_pool: vms

cinder_backends:
  rbd_volumes:
    volume_driver: cinder.volume.drivers.rbd.RBDDriver
    rbd_pool: volumes
    rbd_ceph_conf: /etc/ceph/ceph.conf
    rbd_store_chunk_size: 8
    volume_backend_name: rbddriver
    rbd_user: "{{ cinder_ceph_client }}"
    rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
    report_discard_supported: true

## Common Ceph Overrides
ceph_mons:
    - 172.29.236.71
    - 172.29.236.72
    - 172.29.236.73

## HAProxy and keepalived
haproxy_keepalived_external_vip_cidr: "{{external_lb_vip_address}}/32"
haproxy_keepalived_internal_vip_cidr: "{{internal_lb_vip_address}}/32"
haproxy_keepalived_external_interface: br-mgmt
haproxy_keepalived_internal_interface: br-mgmt

## Customize Nova config
nova_reserved_host_memory_mb: 1024
nova_ram_allocation_ratio: 1.8
nova_cpu_allocation_ratio: 6.0
