# Vagrant file for kolla-ansible
# Last modify 2024/03/12
# Version 1.1

IMAGE_NAME = "bento/ubuntu-22.04"
VM_RAM = "8192" # Define VM memory
VM_CPU = "8" # Define VM CPU
NetworkInterface = "ens160"
OpenStackDeploy = 1 # Define number of deploy
OpenStackNode = 3 # Define number of node

ENV['VAGRANT_NO_PARALLEL'] = 'yes' # For don't run concurrency

Vagrant.configure("2") do |config|

    (1..OpenStackNode).each do |node_id|
        config.vm.define "ka-node-#{node_id}" do |node_vm|
        node_vm.vm.box = IMAGE_NAME
        node_vm.vm.box_check_update = true
        node_vm.vm.hostname = "ka-node-#{node_id}"
        node_vm.vm.network "public_network", bridge: NetworkInterface
        node_vm.vm.network "public_network", bridge: NetworkInterface
        node_vm.vm.disk :disk, size: "65GB", name: "cinder_storage" # Second disk for cinder-volumes
        node_vm.vm.provider "virtualbox" do |vb|
            vb.name = "ka-node-#{node_id}"
            vb.memory = VM_RAM
            vb.cpus = VM_CPU
            end
        node_vm.vm.provision "file", source: "config/02-static-#{node_id}.yaml", destination: "/home/vagrant/02-static.yaml"
        node_vm.vm.provision "shell", path: "script/pre-config-node.sh"
        end
    end

    (1..OpenStackDeploy).each do |deploy_id|
        config.vm.define "ka-deploy-#{deploy_id}" do |deploy_vm|
        deploy_vm.vm.box = IMAGE_NAME
        deploy_vm.vm.box_check_update = true
        deploy_vm.vm.hostname = "ka-deploy-#{deploy_id}"
        deploy_vm.vm.network "public_network", ip: "192.168.9.6#{deploy_id}", bridge: NetworkInterface # For managment network
        deploy_vm.vm.provider "virtualbox" do |vb|
            vb.name = "ka-deploy-#{deploy_id}"
            vb.memory = VM_RAM
            vb.cpus = VM_CPU
            end
        deploy_vm.vm.provision "file", source: "config/globals.yml", destination: "/home/vagrant/globals.yml"
        deploy_vm.vm.provision "file", source: "config/multinode", destination: "/home/vagrant/multinode"
        deploy_vm.vm.provision "file", source: "config/id_rsa.ppk", destination: "/home/vagrant/id_rsa.ppk"
        deploy_vm.vm.provision "file", source: "config/ansible.cfg", destination: "/home/vagrant/ansible.cfg"
        deploy_vm.vm.provision "file", source: "config/passwords.yml", destination: "/home/vagrant/passwords.yml"
        deploy_vm.vm.provision "shell", path: "script/config-deploy-server.sh"
        end
    end

end
