network:
  version: 2
  ethernets:
    eth1:
      addresses:
      - 192.168.9.72/20
      nameservers:
        addresses:
        - 192.168.3.70
        search: []
      routes:
      - to: "default"
        via: 192.168.3.70
    eth2: {}
